version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=foodtruck
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - db_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db

  app:
    image: 'food-truck-management:latest'
    build:
      context: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=foodtruck
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - db

  adminer:
    image: adminer
    ports:
      - "8081:8081"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
networks:
  db:
    driver: bridge
volumes:
  db_data: