#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/compose-postgres
#    username: compose-postgres
#    password: compose-postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: <create>